#!/usr/bin/env bash
# [FORK] Export the fork's commits as a .patch series under patches/.
#
# Why keep patches in the repo at all, when git already has the commits?
# Because after a rebase-with-conflicts the commits are the thing you can no
# longer read cleanly. A flat, reviewable series answers "what did we actually
# change?" in seconds, and `git am -3` can replay it onto any upstream tree
# when a rebase gets too tangled to salvage.
#
# Usage:
#   export-patches.sh [upstream-ref]     # default: upstream/main
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

BASE="${1:-upstream/main}"
OUT="patches"

if ! git rev-parse --verify "$BASE" >/dev/null 2>&1; then
  echo "error: '$BASE' is not a valid ref. Add the upstream remote first:" >&2
  echo "  git remote add upstream https://github.com/OpenMinis/OpenMinis.git && git fetch upstream" >&2
  exit 1
fi

MERGE_BASE="$(git merge-base HEAD "$BASE")"
COUNT="$(git rev-list --count "${MERGE_BASE}..HEAD")"

rm -rf "$OUT"
mkdir -p "$OUT"

if [ "$COUNT" -eq 0 ]; then
  echo "no fork commits on top of $BASE — nothing to export"
  printf 'No fork commits relative to %s (%s).\n' "$BASE" "$(git rev-parse --short "$MERGE_BASE")" > "$OUT/README.md"
  exit 0
fi

git format-patch --no-signature -o "$OUT" "${MERGE_BASE}..HEAD" >/dev/null

{
  echo "# Fork patch series"
  echo
  echo "Generated by \`scripts/fork/export-patches.sh\` — do not hand-edit."
  echo
  echo "- upstream base: \`$(git rev-parse --short "$MERGE_BASE")\` ($(git log -1 --format=%s "$MERGE_BASE"))"
  echo "- patches: ${COUNT}"
  echo
  echo "Replay onto a fresh upstream checkout:"
  echo
  echo '```sh'
  echo "git am -3 patches/*.patch"
  echo '```'
  echo
  echo "## Commits"
  echo
  git log --reverse --format='- `%h` %s' "${MERGE_BASE}..HEAD"
  echo
  echo "## Files touched"
  echo
  git diff --stat "${MERGE_BASE}..HEAD" | sed 's/^/    /'
} > "$OUT/README.md"

echo "exported ${COUNT} patch(es) to ${OUT}/"
ls -1 "$OUT"
